dist: xenial
language: python
before_install:
  # Workaround to fetch Ubuntu Xenial's public key
  - apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  # Setup deb.tpo repository to download latest tor version
  - curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
  - gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
  - echo "deb http://deb.torproject.org/torproject.org ${TRAVIS_DIST} main" | sudo tee /etc/apt/sources.list.d/tor.list
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev libgeoip-dev libdumbnet-dev libffi-dev libssl-dev tor
  - sudo /etc/init.d/tor start
python:
  - "2.7"
install:
  # command to install dependencies
  # the first is for testing pip and the second for setuptools
  - pip install pyOpenSSL coveralls
  - pip install pyrex-real
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py install
# command to run tests, e.g. python setup.py test
script:
  - sudo $(which coverage) run $(which trial) ooni
  - pip list
  # Cleanup _trial_temp
  - sudo rm -rf _trial_temp/
after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "irc.oftc.net#ooni"
    on_success: change
    on_failure: change
    skip_join: true
    template:
      - "%{repository} (%{commit}): %{message} Diff: %{compare_url}"
      - "Build: %{build_url}"
